"""modified column Ads.construction_year to Number

Revision ID: 22b2d1e2b9b3
Revises: 45c5d7eae0fc
Create Date: 2018-09-13 18:13:14.115836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b2d1e2b9b3'
down_revision = '45c5d7eae0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ads_construction_year'), 'ads', ['construction_year'], unique=False)
    op.create_index(op.f('ix_ads_is_active'), 'ads', ['is_active'], unique=False)
    op.create_index(op.f('ix_ads_oblast_district'), 'ads', ['oblast_district'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_oblast_district'), table_name='ads')
    op.drop_index(op.f('ix_ads_is_active'), table_name='ads')
    op.drop_index(op.f('ix_ads_construction_year'), table_name='ads')
    # ### end Alembic commands ###
