"""initial data

Revision ID: 45c5d7eae0fc
Revises: 
Create Date: 2018-09-10 20:36:42.756755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c5d7eae0fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement', sa.String(length=64), nullable=True),
    sa.Column('under_construction', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=264), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('oblast_district', sa.String(length=264), nullable=True),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('construction_year', sa.Date(), nullable=True),
    sa.Column('rooms_number', sa.Integer(), nullable=True),
    sa.Column('premise_area', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_has_balcony'), 'ads', ['has_balcony'], unique=False)
    op.create_index(op.f('ix_ads_price'), 'ads', ['price'], unique=False)
    op.create_index(op.f('ix_ads_settlement'), 'ads', ['settlement'], unique=False)
    op.create_index(op.f('ix_ads_under_construction'), 'ads', ['under_construction'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_under_construction'), table_name='ads')
    op.drop_index(op.f('ix_ads_settlement'), table_name='ads')
    op.drop_index(op.f('ix_ads_price'), table_name='ads')
    op.drop_index(op.f('ix_ads_has_balcony'), table_name='ads')
    op.drop_table('ads')
    # ### end Alembic commands ###
